name: root_hub_flutter
description: A new Flutter project with Serverpod.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: "^3.8.0"
  flutter: "^3.32.0"

resolution: workspace

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  google_fonts: ^8.0.2
  root_hub_client:
    path: ../root_hub_client
  serverpod_auth_idp_flutter: 3.3.1
  serverpod_flutter: 3.3.1
  babel_text: ^2.1.0
  go_router: ^17.1.0
  adaptive_dialog: ^2.6.0
  synchronized: ^3.4.0
  shared_preferences: ^2.5.4

  # Talker
  talker: ^5.1.12
  talker_flutter: ^5.1.12
  talker_riverpod_logger: ^5.1.12

  # State
  flutter_riverpod: ^3.2.1
  riverpod: ^3.2.1
  freezed_annotation: ^3.1.0
  result_dart: ^2.1.1

dev_dependencies:
  build_runner: ^2.11.1
  flutter_lints: ">=3.0.0 <7.0.0"
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/config.json
    - assets/faction_boards/
    - assets/faction_icons/
