services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: root_hub
      POSTGRES_PASSWORD: "H75sysbKRXlH5s0lekehHKx83-YKEQy6"
    volumes:
      - root_hub_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "w49JZrVMebXdJL5ZSK7ugdsM8YD4Hwzc"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: root_hub_test
      POSTGRES_PASSWORD: "m3gklXuNPf72jpaB-5pqrwCPPgteNXox"
    volumes:
      - root_hub_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "jZn3YvAh75uvb9QUZG0as6jxXwsRxAOG"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  root_hub_data:
  root_hub_test_data:
